server:
  port: 5000
  servlet:
    context-path: /yolp

spring:
  application:
    name: yolp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${{ secrets.POSTGRESQL_URL }}
    username: postgres
    password: ${{ secrets.POSTGRESQL_PASSWORD }}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update